### ISSUE TITLE
publish all gists below a single one

### ISSUE THREAD

**Issue by caioaao** [JacobBennett/MarkdownToMedium#7]
Github supports multiple files inside a single gist, like this: https://gist.github.com/mattboldt/7621795
I don't know if this is really an issue, but I'm concerned with replacing a gist when there's a name clash. We also get a cleaner gist list

**Comment by JacobBennett** [comment]
Hey @caioaao thanks for the idea. The problem with Medium is that it will embed every single gist from a gist URL into the medium post at the location that you paste that gist URL. Since that is the case, we couldn't do what we are currently doing which is replacing any code blocks with an inline link to the gist that was created for that specific block. 

Hopefully that makes sense. Also, there would never be a naming collision that would overwrite anything. The names and the IDs of the gists are not the same and the names are not required to be unique across all of your gists. Thanks!
