### ISSUE TITLE
Regardless of text submitted, Medium ends up displaying content from gist.github.com page rather than submission

### ISSUE THREAD

**Issue by technoplato** [JacobBennett/MarkdownToMedium#8]
# Picture is worth 1,000 words

![image](https://user-images.githubusercontent.com/6922904/41821431-c93c961c-77ae-11e8-86c6-50c8d12b2f66.png)

**Comment by JacobBennett** [comment]
Cannot duplicate issue. Can you copy and paste into this issue the Markdown you are using initially?

![image](https://user-images.githubusercontent.com/1517011/42396589-e7e473aa-8127-11e8-88ba-b541ae8b1d35.png)

**Comment by JeremyPlease** [comment]
@JacobBennett Thanks for building this awesome tool! I'm also running into this reported issue. Here are the details:

### Markdown input:

    # This is a test

    Hello and welcome to the `test`.

    ```js
    this.test();
    ```

    <img src="https://homepages.cae.wisc.edu/~ece533/images/airplane.png" />

    1. one 
    2. two 
    3. three

### Generated Gist:

https://gist.github.com/41b5112eefcabd1a87a657cace2f2024

### Imported story:

<img src="https://f.jerm.me/lOWpP5.png" />


It seems like Medium imports the full gist page instead of the markdown preview content. How did you get it to work in your last screenshot? Please let me know if I can provide any other details.

**Comment by technoplato** [comment]
Sorry if this is slightly off topic but I think I got this or a similar Markdown Medium submission program to work. Will post back here shortly with replication details.

**Comment by technoplato** [comment]
Here's the tool that I used that worked @JeremyPlease: https://github.com/yoshuawuyts/markdown-to-medium

@JacobBennett As @JeremyPlease posted, the tool is grabbing the content of the gist webpage rather than the gist itself. The markdown he provided is not different enough from mine to be significant.

Hope that helps.

**Comment by woojoo666** [comment]
fyi another way, is to take the generated markdown gist and put it in a different website that supports markdown previews (I used penflip), and import it to Medium from there

**Comment by JacobBennett** [comment]
Hey all, this is now fixed. Was due to old expiring tokens from GitHub. Should be able to re-login and get the tool to work successfully. Thanks so much for your patience!
